/**
 * The fonts a slide can use, and how to name them in CSS.
 *
 * Every family here is self-hosted by `src/styles/slide-fonts.css` (generated by
 * `scripts/build-slide-fonts-css.mjs`), so a slide renders in the font the
 * operator picked on the projector, the NDI machine and offline — not in
 * whatever the output machine happens to have installed. Adding a family means
 * adding it to both lists; `fonts.test.ts` checks they agree.
 *
 * The family string is what slides, templates and settings store, and what
 * TipTap writes into saved slide HTML, so these names never change. "Source
 * Sans Pro" is served from Source Sans 3's files and "Georgia" from Gelasio's
 * when Georgia isn't installed; see the generator for why.
 */

export interface SlideFont {
    /** The stored, CSS-facing family name. */
    family: string
    /** Generic family for the fallback stack. */
    fallback: 'sans-serif' | 'serif'
}

export const SLIDE_FONTS: readonly SlideFont[] = [
    { family: 'Inter', fallback: 'sans-serif' },
    { family: 'Roboto', fallback: 'sans-serif' },
    { family: 'Open Sans', fallback: 'sans-serif' },
    { family: 'Lato', fallback: 'sans-serif' },
    { family: 'Montserrat', fallback: 'sans-serif' },
    { family: 'Source Sans Pro', fallback: 'sans-serif' },
    { family: 'Poppins', fallback: 'sans-serif' },
    { family: 'Nunito', fallback: 'sans-serif' },
    { family: 'Raleway', fallback: 'sans-serif' },
    { family: 'Ubuntu', fallback: 'sans-serif' },
    { family: 'Georgia', fallback: 'serif' },
    { family: 'Playfair Display', fallback: 'serif' },
]

export const DEFAULT_SLIDE_FONT = 'Inter'

const GENERIC_FAMILIES = new Set([
    'serif', 'sans-serif', 'monospace', 'cursive', 'fantasy', 'system-ui',
    'ui-serif', 'ui-sans-serif', 'ui-monospace', 'ui-rounded', 'emoji', 'math',
])

/**
 * A complete, valid CSS font-family value for a stored font name: the family
 * quoted, then its generic fallback.
 *
 * Quoting matters: a family left bare is only valid CSS when every word in it
 * is an identifier, so a name like "Source Sans 3" makes the whole declaration
 * invalid — and assigning an invalid `ctx.font` is silently ignored, leaving
 * the canvas on its previous font.
 *
 * A value that is already a stack (it contains a comma) is returned as is.
 */
export function cssFontStack(font: string | undefined | null): string {
    const name = (font ?? '').trim() || DEFAULT_SLIDE_FONT
    if (name.includes(',')) return name
    if (GENERIC_FAMILIES.has(name.toLowerCase())) return name
    const known = SLIDE_FONTS.find((f) => f.family.toLowerCase() === name.toLowerCase())
    const unquoted = name.replace(/^(['"])(.*)\1$/, '$2')
    const quoted = `"${unquoted.replace(/["\\]/g, '\\$&')}"`
    return `${quoted}, ${known?.fallback ?? 'sans-serif'}`
}

/**
 * Wait until a family's slide weights are loaded, so a canvas draw measures and
 * paints the real font rather than a fallback. Resolves quietly where the Font
 * Loading API is missing (tests) or the family isn't self-hosted.
 */
export async function loadSlideFont(font: string | undefined | null): Promise<void> {
    if (typeof document === 'undefined' || !document.fonts?.load) return
    const stack = cssFontStack(font)
    try {
        await Promise.all(
            ['400', '600', '700'].flatMap((weight) => [
                document.fonts.load(`${weight} 32px ${stack}`),
                document.fonts.load(`italic ${weight} 32px ${stack}`),
            ]),
        )
    } catch {
        // A face that fails to load falls back like any other missing font.
    }
}
