// Generated by scripts/calibrate-embedding-scores.mjs — do not edit by hand.
// Maps onnx-community/embeddinggemma-300m-ONNX cosine scores onto Xenova/all-MiniLM-L6-v2's scale by
// quantile matching over 1151 queries × top 10 against the
// WEB pack (31100 verses). See scoreCalibration.ts.

export const SCORE_CALIBRATION: {
    modelId: string
    referenceModelId: string
    knots: ReadonlyArray<readonly [number, number]>
} = {
    modelId: 'onnx-community/embeddinggemma-300m-ONNX',
    referenceModelId: 'Xenova/all-MiniLM-L6-v2',
    knots: [
        [0.2846, 0.3071],
        [0.3455, 0.3624],
        [0.3732, 0.3868],
        [0.419, 0.4347],
        [0.4486, 0.4798],
        [0.4777, 0.5222],
        [0.4946, 0.5513],
        [0.51, 0.5722],
        [0.5246, 0.5911],
        [0.541, 0.6113],
        [0.5606, 0.6346],
        [0.5903, 0.6636],
        [0.6127, 0.6848],
        [0.6558, 0.7198],
        [0.7129, 0.766],
        [0.7551, 0.8152],
        [0.799, 0.8689],
        [0.8252, 0.9022],
        [0.8588, 0.9359],
        [0.8781, 0.9547],
        [0.9066, 0.9796],
        [0.9265, 0.9931],
    ],
}
