import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  globalIgnores([
    'dist',
    // Rust build output. Cargo drops Tauri's codegen asset blobs and CMake's
    // `compiler_depend.ts` in here with .js/.ts extensions, so `eslint .`
    // tried to parse a thousand binary files — enough noise to bury every
    // real finding. Only present after a local desktop build, which is
    // exactly when someone is most likely to run lint.
    'src-tauri/target',
    // Generated by `convex dev`/`codegen`; not ours to fix.
    'convex/_generated',
  ]),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    rules: {
      // A leading underscore marks a binding as deliberately unused (a
      // callback parameter the signature requires, a destructured-away field).
      '@typescript-eslint/no-unused-vars': ['error', {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
        caughtErrorsIgnorePattern: '^_',
        destructuredArrayIgnorePattern: '^_',
        ignoreRestSiblings: true,
      }],
    },
  },
  {
    // Test doubles stand in for real modules; typing every mock precisely buys
    // nothing and hides what the test is about.
    files: ['**/__tests__/**', '**/*.test.{ts,tsx}', 'src/test-setup.ts'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },
])
