import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'
import { renderHook, waitFor } from '@testing-library/react'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { useDictionary, useDictionaryPacks, invalidateDictionaryCache } from '../useDictionary'
import { parseDictionaryIndex, searchDictionaryIndex, type RawDictionaryIndex } from '../../lib/search/dictionarySearch'

/**
 * These run against the real packs in `public/dictionaries/`, not fixtures.
 *
 * The packs are generated by a script and committed, so the failure this
 * guards against is a build-script change that quietly breaks the client
 * contract — a renamed shard, a key normalised differently, a manifest format
 * bump. A fixture would keep passing through all of those.
 */
const PACK_ROOT = join(process.cwd(), 'public', 'dictionaries')

// Serve the bundled files the way the browser would.
const fetchMock = vi.fn(async (url: string) => {
    const path = join(PACK_ROOT, url.replace(/^\/dictionaries\//, ''))
    try {
        const body = readFileSync(path, 'utf8')
        return { ok: true, json: async () => JSON.parse(body) } as Response
    } catch {
        return { ok: false, status: 404, json: async () => null } as unknown as Response
    }
})

// IndexedDB isn't available in the test environment; the hook is written to
// treat that as "no cache" and fall through to the bundled asset, which is
// exactly the path being exercised here.
vi.mock('../useIndexedDB', () => ({
    getIndexedDB: () => {
        throw new Error('IndexedDB unavailable')
    },
}))

describe('useDictionary (against the committed packs)', () => {
    beforeEach(() => {
        invalidateDictionaryCache()
        fetchMock.mockClear()
        vi.stubGlobal('fetch', fetchMock)
    })

    afterEach(() => {
        vi.unstubAllGlobals()
    })

    it('loads the manifest and reports every bundled pack', async () => {
        const { result } = renderHook(() => useDictionaryPacks())

        await waitFor(() => expect(result.current.loading).toBe(false))

        const ids = result.current.packs.map((pack) => pack.id)
        expect(ids).toContain('easton')
        expect(ids).toContain('strongs-greek')
        expect(ids).toContain('webster')
        for (const pack of result.current.packs) {
            expect(pack.attribution).toBeTruthy()
            expect(pack.entryCount).toBeGreaterThan(0)
            expect(pack.shards.length).toBeGreaterThan(0)
        }
    })

    it('resolves an Easton\'s entry with its scripture references', async () => {
        const { result } = renderHook(() => useDictionary())

        const entry = await result.current.getEntry('easton', 'Aaron')

        expect(entry?.word).toBe('Aaron')
        expect(entry?.senses[0].text).toContain('Amram')
        expect(entry?.refs?.length).toBeGreaterThan(0)
    })

    it('resolves a Greek entry by its Strong\'s number, keeping the lemma', async () => {
        const { result } = renderHook(() => useDictionary())

        const entry = await result.current.getEntry('strongs-greek', 'G26')

        expect(entry?.word).toBe('ἀγάπη')
        expect(entry?.transliteration).toBe('agápē')
        expect(entry?.strongs).toBe('G26')
    })

    it('finds the same word across several packs at once', async () => {
        const { result } = renderHook(() => useDictionary())

        const entries = await result.current.getEntries(['easton', 'smith', 'webster'], 'Aaron')

        // Webster's has no "Aaron"; the packs that do are returned, not an error.
        expect(entries.map((entry) => entry.packId)).toEqual(['easton', 'smith'])
    })

    it('returns null for a word no pack defines', async () => {
        const { result } = renderHook(() => useDictionary())

        expect(await result.current.getEntry('easton', 'qwertyuiop')).toBeNull()
    })

    it('fetches each file once and serves repeats from memory', async () => {
        const { result } = renderHook(() => useDictionary())

        await result.current.getEntry('easton', 'Aaron')
        await result.current.getEntry('easton', 'Abaddon')
        await result.current.getEntry('easton', 'Aaron')

        // All three keys live in the "a" shard — one fetch total.
        expect(fetchMock).toHaveBeenCalledTimes(1)
        expect(fetchMock).toHaveBeenCalledWith('/dictionaries/easton/a.json')
    })

    it('collapses concurrent first loads of the same shard into one fetch', async () => {
        const { result } = renderHook(() => useDictionary())

        await Promise.all([
            result.current.getEntry('easton', 'Aaron'),
            result.current.getEntry('easton', 'Abel'),
            result.current.getEntry('easton', 'Abraham'),
        ])

        expect(fetchMock).toHaveBeenCalledTimes(1)
    })

    it('keeps every index key resolvable in the shard the client computes', async () => {
        const { result } = renderHook(() => useDictionary())
        const raw = JSON.parse(
            readFileSync(join(PACK_ROOT, 'easton', 'index.json'), 'utf8'),
        ) as RawDictionaryIndex
        const index = parseDictionaryIndex(raw)

        // Spot-check across the alphabet rather than all 3,961 — enough to catch
        // a normalisation or sharding divergence, fast enough for CI.
        const sample = index.records.filter((_, i) => i % 97 === 0)
        expect(sample.length).toBeGreaterThan(20)

        for (const record of sample) {
            const entry = await result.current.getEntry(record.packId, record.key)
            expect(entry, `no entry for ${record.key}`).not.toBeNull()
        }
        // Reads and parses all 25 Easton's shards — past the 5s default when
        // the suite is running other files in parallel.
    }, 30_000)

    it('searches the real Webster index by prefix', async () => {
        const { result } = renderHook(() => useDictionary())
        const index = await result.current.loadIndex('webster')

        const hits = searchDictionaryIndex(index!, 'propitiat', 10)

        expect(hits.map((hit) => hit.record.word)).toContain('propitiation')
        // Fetching and parsing 102k headwords is ~2.5s of real work; the panel
        // pays it on open rather than on the first keystroke.
    }, 30_000)
})
