/**
 * A real worship song, as the pipeline actually hears it.
 *
 * `PRAYER_ANSWERING_GOD` is the song as the library stores it. `HEARD` is the
 * transcript produced by replaying a 9:21 recording of it through the shipping
 * capture pipeline and `parakeet-unified-en-0.6b` — see
 * `src-tauri/src/audio_capture/offline_probe.rs`. Every line is verbatim engine
 * output at the timestamp it arrived; nothing is cleaned up or invented.
 *
 * This exists because matching was previously tuned against errors we imagined
 * rather than the ones this pipeline makes. Roughly a sixth of the segments
 * decode to nothing and a good share of the rest are wrong in ways no lexical
 * scorer recovers ("burden" -> "birds", "victory" -> "slavery"), which is the
 * real input the tracker has to stay locked through.
 */

export const PRAYER_ANSWERING_GOD_LYRICS = [
    'I will look to the Hills, Mountains and Valleys',
    'From where comes my help',
    'From no one but you',
    '',
    'I have searched and searched Through humanity',
    'Is there one like you?',
    "There's no one like you",
    '',
    'How you love me',
    'No one knows how far it goes',
    "You've said in your Word",
    "Ask and you'll receive",
    'All your heart desire',
    'You supply all my needs',
    '',
    'I go carry my burden to you',
    'Victory is in your hands',
    'I know you will never let me down',
    'I go carry my problems to you',
    'Favour is in your hands',
    "I know you won't send me away",
    '',
    'I go de carry my Yoke to you',
    'Freedom is in your hands',
    'I know you will never let me down',
    'I Go de Carry my praise to you',
    'Victory is in your hands',
    "I know you won't send me away",
    '',
    'You are a prayer answering God',
    'You have heard me',
].join('\n')

/** Verbatim engine output, in arrival order, with its position in the song. */
export const HEARD: Array<{ atMs: number; text: string }> = [
    { atMs: 5000, text: 'Hallelujah.' },
    { atMs: 14000, text: 'Precious Jesus' },
    { atMs: 19000, text: 'Give you' },
    { atMs: 44000, text: 'I could look to the hills, mountains and valleys' },
    { atMs: 49000, text: 'From whence come my help?' },
    { atMs: 52000, text: 'From no one but you' },
    { atMs: 56000, text: 'I have searched and searched through humanity Is there one like you?' },
    { atMs: 64000, text: 'There\'s no one like you' },
    { atMs: 67000, text: 'Yeah' },
    { atMs: 71000, text: 'How?' },
    { atMs: 72000, text: 'You love me, no one knows.' },
    { atMs: 76000, text: 'How far it goes' },
    { atMs: 81000, text: 'You have said in your word, ask and you receive all your heart desire. You supply all my needs.' },
    { atMs: 91000, text: 'Sing how' },
    { atMs: 95000, text: 'Yeah.' },
    { atMs: 100000, text: 'How far it goes Sing how' },
    { atMs: 110000, text: 'How you look?' },
    { atMs: 128000, text: 'Okay.' },
    { atMs: 129000, text: 'Hey, you are sending me away.' },
    { atMs: 134000, text: 'You supply all my needs' },
    { atMs: 140000, text: 'Hey, I go kind of.' },
    { atMs: 145000, text: 'Yeah.' },
    { atMs: 146000, text: 'Victory is in your hands.' },
    { atMs: 151000, text: 'I don\'t know if you will.' },
    { atMs: 158000, text: 'But you' },
    { atMs: 162000, text: 'I know you won\'t ever Jesus I won\'t carry my' },
    { atMs: 169000, text: 'To you, freedom is in your hands. I know you will never.' },
    { atMs: 176000, text: 'And Lord, you will never.' },
    { atMs: 182000, text: 'To you, victory is in yours.' },
    { atMs: 195000, text: 'How you love it, how far it go.' },
    { atMs: 202000, text: 'Lift it up, say how you love.' },
    { atMs: 208000, text: 'How you love, how you love you love.' },
    { atMs: 215000, text: 'You are sending you all your' },
    { atMs: 221000, text: 'All your heart desire, you supply my needs, Jesus Christ.' },
    { atMs: 228000, text: 'Jesus, you are setting your word on your heart.' },
    { atMs: 234000, text: 'All your heart desire, you supply all my needs.' },
    { atMs: 241000, text: 'To you, victory is in your hand.' },
    { atMs: 247000, text: 'I know you will never say I forgot.' },
    { atMs: 254000, text: 'I forecover my problem to you. Savor is in your hands.' },
    { atMs: 260000, text: 'Your hands, I know you will never last so tired. I will carry my.' },
    { atMs: 267000, text: 'I\'m gonna carry my over to you. Freedom is where you are.' },
    { atMs: 273000, text: 'I know you will never, my son, I must carry my prayer.' },
    { atMs: 280000, text: 'I read my prayer to you. Victory is in your hands.' },
    { atMs: 287000, text: 'I know you have a' },
    { atMs: 295000, text: 'Rayo.' },
    { atMs: 296000, text: 'Answering God, you have heard me. Hey, you have heard me. Is that very' },
    { atMs: 302000, text: 'It\'s a very simple song. Can you sing with me? You are prayer answering, God.' },
    { atMs: 309000, text: 'Come on, lift.' },
    { atMs: 315000, text: 'Come on, lift your watch. You are prayer. You have heard me.' },
    { atMs: 322000, text: 'You have heard me and you have heard me when I call you on my knee.' },
    { atMs: 329000, text: 'You\'re on my knees, you are afraid You have heard me.' },
    { atMs: 335000, text: 'Hurt me, and you have heard me when I call you in the morning, you' },
    { atMs: 342000, text: 'Good morning, you are prayer and sorry.' },
    { atMs: 348000, text: 'And you have heard me. I will cast my burdens upon you. You are.' },
    { atMs: 361000, text: 'When I lift my hands in the secret place, you are a prayer.' },
    { atMs: 368000, text: 'You are a prayer and you have heard.' },
    { atMs: 374000, text: 'And you have heard Messiah.' },
    { atMs: 387000, text: 'You have heard it and you have heard it I will cast my crown' },
    { atMs: 394000, text: 'That\'s my crown. You will never leave me behind. Your name is your name.' },
    { atMs: 407000, text: 'Name Jesus every knee shall bow every side shall confess' },
    { atMs: 413000, text: 'You are a living God is a man.' },
    { atMs: 420000, text: 'That you shut your love upon it. That you shut your peace upon it.' },
    { atMs: 426000, text: 'And you have heard I will lift.' },
    { atMs: 433000, text: 'I will lift up my prayer. You will not walk away. You will not lift up.' },
    { atMs: 440000, text: 'You wanna live this trend You have hope and you have hope' },
    { atMs: 446000, text: 'And you have heard and you have heard Sakadaba.' },
    { atMs: 462000, text: 'Answering God.' },
    { atMs: 465000, text: 'You have heard me' },
    { atMs: 472000, text: 'What you came here with tonight.' },
    { atMs: 475000, text: 'He is their prayer answering God.' },
    { atMs: 479000, text: 'He has heard you He has heard you.' },
    { atMs: 484000, text: 'That you are praying to God about' },
    { atMs: 487000, text: 'He is our prayer answering God.' },
    { atMs: 491000, text: 'He has heard you.' },
    { atMs: 495000, text: 'Turn you.' },
    { atMs: 498000, text: 'Spirit, somebody is here. You are battling with a disease. He is a prayer-ans.' },
    { atMs: 504000, text: 'Sir, he has heard you has heard you some of you.' },
    { atMs: 511000, text: 'Some of you, you are beginning to doubt God. You are asking God, Father, where is my life going? Where is my life going?' },
    { atMs: 517000, text: 'Where is my education going? I have been staying home for the past six months. What am I doing with my life?' },
    { atMs: 524000, text: 'What am I doing with my life? Father, I need direction. He is a prayer answering God.' },
    { atMs: 537000, text: 'You came here with a prayer point.' },
    { atMs: 544000, text: 'Came here with the prayer point. Begin to lift that prayer. Begin to lift that prayer.' },
    { atMs: 550000, text: 'Masotakama Malata Kama Masotay Matoka Mayata Econo.' },]
