/**
 * A real worship song, as the pipeline actually hears it.
 *
 * `PRAYER_ANSWERING_GOD` is the song as the library stores it. `HEARD` is the
 * transcript produced by replaying a 9:21 recording of it through the shipping
 * capture pipeline and `parakeet-unified-en-0.6b` — see
 * `src-tauri/src/audio_capture/offline_probe.rs`. Every line is verbatim engine
 * output at the timestamp it arrived; nothing is cleaned up or invented.
 *
 * This exists because matching was previously tuned against errors we imagined
 * rather than the ones this pipeline makes. Roughly a sixth of the segments
 * decode to nothing and a good share of the rest are wrong in ways no lexical
 * scorer recovers ("burden" -> "birds", "victory" -> "slavery"), which is the
 * real input the tracker has to stay locked through.
 */

export const PRAYER_ANSWERING_GOD_LYRICS = [
    'I will look to the Hills, Mountains and Valleys',
    'From where comes my help',
    'From no one but you',
    '',
    'I have searched and searched Through humanity',
    'Is there one like you?',
    "There's no one like you",
    '',
    'How you love me',
    'No one knows how far it goes',
    "You've said in your Word",
    "Ask and you'll receive",
    'All your heart desire',
    'You supply all my needs',
    '',
    'I go carry my burden to you',
    'Victory is in your hands',
    'I know you will never let me down',
    'I go carry my problems to you',
    'Favour is in your hands',
    "I know you won't send me away",
    '',
    'I go de carry my Yoke to you',
    'Freedom is in your hands',
    'I know you will never let me down',
    'I Go de Carry my praise to you',
    'Victory is in your hands',
    "I know you won't send me away",
    '',
    'You are a prayer answering God',
    'You have heard me',
].join('\n')

/** Verbatim engine output, in arrival order, with its position in the song. */
export const HEARD: Array<{ atMs: number; text: string }> = [
    { atMs: 5000, text: 'Hallelujah.' },
    { atMs: 14000, text: 'Precious Jesus' },
    { atMs: 19000, text: 'Give you' },
    { atMs: 44000, text: 'I could look to the hills, mountains and valleys' },
    { atMs: 49000, text: 'From whence come my help?' },
    { atMs: 52000, text: 'From no one but you' },
    { atMs: 56000, text: 'I have searched and searched through humanity Is there one like you?' },
    { atMs: 64000, text: 'There\'s no one like you' },
    { atMs: 67000, text: 'Yeah' },
    { atMs: 71000, text: 'How?' },
    { atMs: 72000, text: 'You love me, no one knows.' },
    { atMs: 76000, text: 'How far it goes' },
    { atMs: 81000, text: 'You have said in your word, ask and you receive all your heart desire. You supply all my needs.' },
    { atMs: 91000, text: 'Sing how' },
    { atMs: 95000, text: 'Yeah.' },
    { atMs: 100000, text: 'How far it goes Sing how' },
    { atMs: 110000, text: 'How you look?' },
    { atMs: 128000, text: 'Okay.' },
    { atMs: 129000, text: 'Hey, you are sending me away.' },
    { atMs: 134000, text: 'You supply all my needs' },
    { atMs: 140000, text: 'Hey, I go kind of.' },
    { atMs: 145000, text: 'Yeah.' },
    { atMs: 146000, text: 'Victory is in your hands.' },
    { atMs: 151000, text: 'I don\'t know if you will.' },
    { atMs: 158000, text: 'But you' },
    { atMs: 162000, text: 'I know you won\'t ever Jesus I won\'t carry my' },
    { atMs: 169000, text: 'To you, freedom is in your hands. I know you will never.' },
    { atMs: 176000, text: 'And Lord, you will never.' },
    { atMs: 182000, text: 'To you, victory is in yours.' },
    { atMs: 195000, text: 'How you love it, how far it go.' },
    { atMs: 202000, text: 'Lift it up, say how you love.' },
    { atMs: 208000, text: 'How you love, how you love you love.' },
    { atMs: 215000, text: 'You are sending you all your' },
    { atMs: 221000, text: 'All your heart desire, you supply my needs, Jesus Christ.' },
    { atMs: 228000, text: 'Jesus, you are setting your word on your heart.' },
    { atMs: 234000, text: 'All your heart desire, you supply all my needs.' },
    { atMs: 241000, text: 'To you, victory is in your hand.' },
    { atMs: 247000, text: 'I know you will never say I forgot.' },
    { atMs: 254000, text: 'I forecover my problem to you. Savor is in your hands.' },
    { atMs: 260000, text: 'Your hands, I know you will never last so tired. I will carry my.' },
    { atMs: 267000, text: 'I\'m gonna carry my over to you. Freedom is where you are.' },
    { atMs: 273000, text: 'I know you will never, my son, I must carry my prayer.' },
    { atMs: 280000, text: 'I read my prayer to you. Victory is in your hands.' },
    { atMs: 287000, text: 'I know you have a' },
    { atMs: 295000, text: 'Rayo.' },
    { atMs: 296000, text: 'Answering God, you have heard me. Hey, you have heard me. Is that very' },
    { atMs: 302000, text: 'It\'s a very simple song. Can you sing with me? You are prayer answering, God.' },
    { atMs: 309000, text: 'Come on, lift.' },
    { atMs: 315000, text: 'Come on, lift your watch. You are prayer. You have heard me.' },
    { atMs: 322000, text: 'You have heard me and you have heard me when I call you on my knee.' },
    { atMs: 329000, text: 'You\'re on my knees, you are afraid You have heard me.' },
    { atMs: 335000, text: 'Hurt me, and you have heard me when I call you in the morning, you' },
    { atMs: 342000, text: 'Good morning, you are prayer and sorry.' },
    { atMs: 348000, text: 'And you have heard me. I will cast my burdens upon you. You are.' },
    { atMs: 361000, text: 'When I lift my hands in the secret place, you are a prayer.' },
    { atMs: 368000, text: 'You are a prayer and you have heard.' },
    { atMs: 374000, text: 'And you have heard Messiah.' },
    { atMs: 387000, text: 'You have heard it and you have heard it I will cast my crown' },
    { atMs: 394000, text: 'That\'s my crown. You will never leave me behind. Your name is your name.' },
    { atMs: 407000, text: 'Name Jesus every knee shall bow every side shall confess' },
    { atMs: 413000, text: 'You are a living God is a man.' },
    { atMs: 420000, text: 'That you shut your love upon it. That you shut your peace upon it.' },
    { atMs: 426000, text: 'And you have heard I will lift.' },
    { atMs: 433000, text: 'I will lift up my prayer. You will not walk away. You will not lift up.' },
    { atMs: 440000, text: 'You wanna live this trend You have hope and you have hope' },
    { atMs: 446000, text: 'And you have heard and you have heard Sakadaba.' },
    { atMs: 462000, text: 'Answering God.' },
    { atMs: 465000, text: 'You have heard me' },
    { atMs: 472000, text: 'What you came here with tonight.' },
    { atMs: 475000, text: 'He is their prayer answering God.' },
    { atMs: 479000, text: 'He has heard you He has heard you.' },
    { atMs: 484000, text: 'That you are praying to God about' },
    { atMs: 487000, text: 'He is our prayer answering God.' },
    { atMs: 491000, text: 'He has heard you.' },
    { atMs: 495000, text: 'Turn you.' },
    { atMs: 498000, text: 'Spirit, somebody is here. You are battling with a disease. He is a prayer-ans.' },
    { atMs: 504000, text: 'Sir, he has heard you has heard you some of you.' },
    { atMs: 511000, text: 'Some of you, you are beginning to doubt God. You are asking God, Father, where is my life going? Where is my life going?' },
    { atMs: 517000, text: 'Where is my education going? I have been staying home for the past six months. What am I doing with my life?' },
    { atMs: 524000, text: 'What am I doing with my life? Father, I need direction. He is a prayer answering God.' },
    { atMs: 537000, text: 'You came here with a prayer point.' },
    { atMs: 544000, text: 'Came here with the prayer point. Begin to lift that prayer. Begin to lift that prayer.' },
    { atMs: 550000, text: 'Masotakama Malata Kama Masotay Matoka Mayata Econo.' },]


/**
 * The same recording, but with the band removed and transcribed by whisper.
 *
 * Produced from an isolated vocal stem of the same nine minutes, through the
 * same pipeline, with `whisper-small` instead of Parakeet. This is what the
 * pipeline could see given a vocal-only feed from the sound desk — the setup
 * this app will meet in a real building, where the operator can send a vocal
 * aux rather than the front-of-house mix.
 *
 * Kept beside {@link HEARD} so a change can be judged against both the input
 * we have and the input we could have: something that only helps the clean
 * case is not much use, and something that only helps the messy one may just
 * be fitting its noise.
 */
export const HEARD_VOCALS_WHISPER: Array<{ atMs: number; text: string }> = [
    { atMs: 8000, text: 'HALA' },
    { atMs: 14000, text: 'Precious Jesus' },
    { atMs: 18000, text: 'We give you all' },
    { atMs: 24000, text: '네 erm Processed In K sun K Cont perceived bye酲 Bian mood wondering' },
    { atMs: 29000, text: 'Mudro' },
    { atMs: 44000, text: 'I\'ll go look to the hills, mountains and valleys' },
    { atMs: 49000, text: 'From whence come my help?' },
    { atMs: 52000, text: 'From no one but you' },
    { atMs: 56000, text: 'I have searched and searched through humanity It\'s the one like you' },
    { atMs: 64000, text: 'There\'s no one like you' },
    { atMs: 67000, text: 'Yeah' },
    { atMs: 69000, text: 'How?' },
    { atMs: 72000, text: 'You' },
    { atMs: 73000, text: 'Love me, no one knows' },
    { atMs: 77000, text: 'How far it goes' },
    { atMs: 81000, text: 'You have said in your word' },
    { atMs: 84000, text: 'Ask and you receive all your heart desire You supply all my needs Sing high' },
    { atMs: 98000, text: 'How you love' },
    { atMs: 100000, text: 'No.' },
    { atMs: 100000, text: 'How far it goes' },
    { atMs: 105000, text: 'Sing how, how, how you love, how you love, how you love no one knows.' },
    { atMs: 118000, text: 'Yeah, standing your word, asking your reason. All your heart desires, you supply all my needs.' },
    { atMs: 128000, text: 'Hey, you are sad in your work. On your heart, teacher.' },
    { atMs: 138000, text: 'I\'m gonna cry on my knees Hey, I\'m gonna cry on my knees' },
    { atMs: 144000, text: 'érie rats하게 hit?' },
    { atMs: 154000, text: 'I will carry my promise to you, favor it in your hair. I know you will.' },
    { atMs: 164000, text: 'Jesus, I\'m going to carry my yoke to you. Freedom is in your hands.' },
    { atMs: 175000, text: 'I know you will never. I know you won\'t ever let me die. I\'m gonna carry my prey. I\'m gonna carry my prey. To you.' },
    { atMs: 185000, text: 'Victory\'s in your hands' },
    { atMs: 189000, text: 'I know you won\'t say anything no more Lift your voice straight out Out' },
    { atMs: 196000, text: 'How are you, love?' },
    { atMs: 209000, text: 'How you love' },
    { atMs: 212000, text: 'No, no!' },
    { atMs: 216000, text: 'You are sending your word, ask and you are sending your word. All your heart desires, you supply all my' },
    { atMs: 226000, text: 'Jesus, you are sad in your way' },
    { atMs: 232000, text: 'Oh, your heart desires, you supply all my needs. Lasso tie a comma.' },
    { atMs: 242000, text: 'were crap' },
    { atMs: 244000, text: 'I\'ll marry my bird to you. Victory\'s in your hands. I know you will never. My poor son.' },
    { atMs: 254000, text: 'AME CHAN念' },
    { atMs: 264000, text: 'I will never let you tire. I will carry my yoke. To you, freedom is where you are.' },
    { atMs: 274000, text: 'Than you are, I add know you will never fine so daya. I\'m gonna carry my prayers To you for the fenders may we deserve it Only oxygen can tank 4. Его to cure it' },
    { atMs: 284000, text: 'I know you won\'t ever, yeah' },
    { atMs: 294000, text: 'And you are a prayer answering God' },
    { atMs: 298000, text: 'You have heard me. Hey!' },
    { atMs: 301000, text: 'You have heard me. It\'s a very simple song. Can you sing with me?' },
    { atMs: 307000, text: 'You are a prayer answering God.' },
    { atMs: 311000, text: 'You have heard me. Hey!' },
    { atMs: 314000, text: 'You have heard me. Come on live to us. You are prayer. You are prayer to him. You have heard me.' },
    { atMs: 324000, text: 'And you have heard me. When I call you on my way.' },
    { atMs: 329000, text: 'You are a prayer and a You have heard this. And you have heard this.' },
    { atMs: 339000, text: 'I\'m going to call you in the' },
    { atMs: 348000, text: 'And you have heard. I will cast my burdens upon you. You are a prayer.' },
    { atMs: 358000, text: 'You have her! You have her! Montaya, you have her! You have her! When I lift my hands up!' },
    { atMs: 366000, text: 'Send us a quick reply You are a prayer You are a prayer You are a serenity You are a' },
    { atMs: 373000, text: 'You have hope! And you have hope!' },
    { atMs: 376000, text: 'Bye!' },
    { atMs: 377000, text: 'Max' },
    { atMs: 380000, text: 'You are a prayer' },
    { atMs: 383000, text: 'That\'s Serena!' },
    { atMs: 386000, text: 'You have heard me. You have heard me. You have heard me. You have heard me. I will cast my cry.' },
    { atMs: 395000, text: 'You have a You will never leave me behind Your name is your name You have a And both of them be of the name' },
    { atMs: 405000, text: 'And the mention of the name Jesus. Every knee shall bow. Every tongue shall contest.' },
    { atMs: 415000, text: 'that your father lived and you try on that your father turned out to love that your father lived and God didn\'t miss' },
    { atMs: 425000, text: 'up on' },
    { atMs: 430000, text: 'Bye!' },
    { atMs: 431000, text: 'And you have a hood!' },
    { atMs: 433000, text: 'I will lift up my prayer You have a You will not walk away You have a You will not live this time that You have a You have a' },
    { atMs: 443000, text: 'You\'ll have a hooo!' },
    { atMs: 446000, text: 'And you have a hooo!' },
    { atMs: 448000, text: 'Take Some consent matters!' },
    { atMs: 449000, text: 'And you have heard!' },
    { atMs: 451000, text: 'Şakadama' },
    { atMs: 461000, text: 'You are a prayer answering God' },
    { atMs: 465000, text: 'You have hurt me.' },
    { atMs: 469000, text: 'You have hurt me' },
    { atMs: 471000, text: 'I don\'t know what you came here with tonight.' },
    { atMs: 475000, text: 'But he is a prayer answer and God' },
    { atMs: 479000, text: 'And he has heard you.' },
    { atMs: 482000, text: 'He has the business that\'s who I pray to God about. He is a prayer answering God.' },
    { atMs: 490000, text: 'Hey!' },
    { atMs: 491000, text: 'He has heard you' },
    { atMs: 494000, text: 'He has heard you!' },
    { atMs: 497000, text: 'tri rsha l save io sór dot namb ah � lay koi t killed te ke интер jo r ty d' },
    { atMs: 504000, text: 'FAH!!!' },
    { atMs: 505000, text: 'He has heard you.' },
    { atMs: 507000, text: 'MAPOSSA!' },
    { atMs: 509000, text: '네 회사님!' },
    { atMs: 511000, text: '上马 neck' },
    { atMs: 512000, text: 'You are beginning to announce God!' },
    { atMs: 514000, text: 'говор advisor wise my education going high up' },
    { atMs: 520000, text: 'Be steighan-hop!' },
    { atMs: 522000, text: 'for the past six months. What am I doing with my life? Father, I need direction. He is a prayer, I\'m sorry God.' },
    { atMs: 532000, text: 'He has heard you' },
    { atMs: 536000, text: 'He has her.' },
    { atMs: 539000, text: 'He answered and you will hear me. He answered. You came here with the prayer points. He answered. We\'re going to lift the prayer.' },
    { atMs: 548000, text: 'You get a left-out player! My SOTA KABA! My RATA KABA!' },
    { atMs: 554000, text: 'Masùเหager aja Masùsın' },
]
