/**
 * Labeled query sets for the semantic-search scripts (pack eval, score
 * calibration, policy eval). Kept in one place so a model comparison and the
 * calibration that follows it are measured on the same questions.
 *
 *   PARAPHRASE — how people search: modern English, never verbatim from any
 *                translation (verbatim would only measure "is this the KJV").
 *   LIVE       — what the sermon listener actually hears: a transcribed
 *                sentence with the verse quoted or paraphrased inside preacher
 *                talk.
 *   NEGATIVE   — ordinary sermon and service talk that must NOT put a verse on
 *                screen. Heavy on God-talk on purpose: theological vocabulary
 *                without a verse behind it is where false positives come from.
 *                The first entries are production false positives (commit
 *                2c1dec3 and its regression tests).
 */

export const PARAPHRASE = [
    { q: 'god loved the world so much he gave his only son', target: 'John 3:16' },
    { q: 'the lord takes care of me like a shepherd, I have everything I need', target: 'Psalms 23:1' },
    { q: 'even walking through the darkest valley I am not afraid', target: 'Psalms 23:4' },
    { q: 'everything works out for good for people who love god', target: 'Romans 8:28' },
    { q: 'I can do anything because christ gives me strength', target: 'Philippians 4:13' },
    { q: 'trust god completely instead of relying on your own thinking', target: 'Proverbs 3:5' },
    { q: 'saved by grace through faith, not something you earned', target: 'Ephesians 2:8' },
    { q: 'come to me if you are tired and I will give you rest', target: 'Matthew 11:28' },
    { q: 'those who hope in the lord get new strength and fly like eagles', target: 'Isaiah 40:31' },
    { q: 'in the beginning god made the sky and the earth', target: 'Genesis 1:1' },
    { q: 'I am standing at the door knocking', target: 'Revelation 3:20' },
    { q: 'god has plans to give you a future and hope', target: 'Jeremiah 29:11' },
    { q: 'love is patient and kind, it does not envy', target: '1 Corinthians 13:4' },
    { q: 'do not worry about tomorrow', target: 'Matthew 6:34' },
    { q: 'ask and you will receive, knock and the door opens', target: 'Matthew 7:7' },
    { q: 'everyone has sinned and falls short of gods glory', target: 'Romans 3:23' },
    { q: 'the payment for sin is death but gods gift is eternal life', target: 'Romans 6:23' },
    { q: 'if we admit our sins he forgives us and cleans us up', target: '1 John 1:9' },
    { q: 'your word is a lamp for my feet lighting my path', target: 'Psalms 119:105' },
    { q: 'be strong and brave, do not be afraid, god goes with you', target: 'Joshua 1:9' },
    { q: 'god is our safe place and strength, always there in trouble', target: 'Psalms 46:1' },
    { q: 'let your light shine so people see your good works', target: 'Matthew 5:16' },
    { q: 'no condemnation for those who belong to christ', target: 'Romans 8:1' },
    { q: 'if anyone is in christ they are a new creation, the old is gone', target: '2 Corinthians 5:17' },
    { q: 'the fruit of the spirit is love joy peace patience', target: 'Galatians 5:22' },
    { q: 'do not be anxious, pray about everything with thanksgiving', target: 'Philippians 4:6' },
    { q: 'god disciplines the ones he loves', target: 'Hebrews 12:6' },
    { q: 'faith is being sure of what we hope for', target: 'Hebrews 11:1' },
    { q: 'consider it joy when you face different kinds of trials', target: 'James 1:2' },
    { q: 'cast all your worries on him because he cares for you', target: '1 Peter 5:7' },
    { q: 'jesus said I am the way the truth and the life', target: 'John 14:6' },
    { q: 'the truth will set you free', target: 'John 8:32' },
    { q: 'greater love has no one than to lay down his life for friends', target: 'John 15:13' },
    { q: 'we love because he first loved us', target: '1 John 4:19' },
    { q: 'train up a child in the way he should go', target: 'Proverbs 22:6' },
    { q: 'a soft answer turns away anger', target: 'Proverbs 15:1' },
    { q: 'seek first the kingdom of god and everything else gets added', target: 'Matthew 6:33' },
    { q: 'where two or three gather together I am there with them', target: 'Matthew 18:20' },
    { q: 'go and make disciples of all nations', target: 'Matthew 28:19' },
    { q: 'the joy of the lord is my strength', target: 'Nehemiah 8:10' },
]

export const LIVE = [
    { q: 'And church I want you to know this morning that God so loved the world, amen, that he gave his one and only son', target: 'John 3:16' },
    { q: 'Somebody say the Lord is my shepherd, I shall not want, I lack nothing', target: 'Psalms 23:1' },
    { q: "Even when you are walking through the valley of the shadow of death you don't have to fear any evil because he is with you", target: 'Psalms 23:4' },
    { q: 'We know that all things, not some things, all things work together for good to them that love God', target: 'Romans 8:28' },
    { q: 'You can do all things, I said all things, through Christ who strengthens you', target: 'Philippians 4:13' },
    { q: "Don't lean on your own understanding, trust in the Lord with all your heart", target: 'Proverbs 3:5' },
    { q: 'It is by grace you have been saved, through faith, and it is not of yourselves, it is the gift of God', target: 'Ephesians 2:8' },
    { q: 'Jesus is saying to somebody today come unto me all ye that labour and are heavy laden and I will give you rest', target: 'Matthew 11:28' },
    { q: 'They that wait upon the Lord shall renew their strength, they shall mount up with wings as eagles', target: 'Isaiah 40:31' },
    { q: 'For I know the thoughts that I think toward you, thoughts of peace and not of evil, to give you an expected end', target: 'Jeremiah 29:11' },
    { q: 'Behold, he says, I stand at the door and knock, if any man hears my voice and opens the door', target: 'Revelation 3:20' },
    { q: 'Be careful for nothing, but in everything by prayer and supplication with thanksgiving let your requests be made known', target: 'Philippians 4:6' },
    { q: 'If we confess our sins, he is faithful and just to forgive us our sins and to cleanse us from all unrighteousness', target: '1 John 1:9' },
    { q: 'The wages of sin is death, but the gift of God is eternal life through Jesus Christ our Lord', target: 'Romans 6:23' },
    { q: 'All have sinned, all of us, and come short of the glory of God', target: 'Romans 3:23' },
    { q: 'Therefore if any man be in Christ he is a new creature, old things are passed away, behold all things are become new', target: '2 Corinthians 5:17' },
    { q: 'There is therefore now no condemnation to them which are in Christ Jesus, hallelujah', target: 'Romans 8:1' },
    { q: 'Have I not commanded you, be strong and of a good courage, be not afraid, neither be thou dismayed', target: 'Joshua 1:9' },
    { q: 'Casting all your care upon him, for he careth for you, give it to him church', target: '1 Peter 5:7' },
    { q: 'Now faith is the substance of things hoped for, the evidence of things not seen', target: 'Hebrews 11:1' },
    { q: 'Jesus said unto him, I am the way, the truth, and the life, no man cometh unto the Father but by me', target: 'John 14:6' },
    { q: 'Seek ye first the kingdom of God and his righteousness and all these things shall be added unto you', target: 'Matthew 6:33' },
    { q: "Thy word is a lamp unto my feet and a light unto my path, that's what the psalmist says", target: 'Psalms 119:105' },
    { q: 'God is our refuge and strength, a very present help in trouble', target: 'Psalms 46:1' },
    { q: 'Let your light so shine before men that they may see your good works and glorify your Father', target: 'Matthew 5:16' },
    { q: 'The Lord will fight for you, church, you only need to be still', target: 'Exodus 14:14' },
    { q: 'Christ died for you while you were still a sinner, that is how much he loves you', target: 'Romans 5:8' },
    { q: 'God says I will restore to you the years that the locust has eaten', target: 'Joel 2:25' },
]

export const NEGATIVE = [
    // Production false positives.
    'God has left',
    'we are shells',
    'the devil finished somebody',
    // Service talk.
    'Good morning church, it is good to be in the house of the Lord today',
    'Turn to your neighbour and tell them you look blessed',
    'Please remember the youth retreat is next Saturday at nine',
    'The offering baskets will come round during the next song',
    'Can the ushers please help people find seats at the front',
    "Let's give a big hand to the choir for that wonderful ministration",
    'If you are visiting with us for the first time we want to welcome you',
    'Somebody shout hallelujah',
    "Let's stand to our feet as we read",
    'The pastor will be travelling to Kumasi next week',
    'Our building project is almost complete thanks to your giving',
    'Make sure you collect a bulletin on your way out',
    'Please put your phones on silent',
    'I want everybody to lift up your hands',
    "The children's church is meeting in the hall downstairs",
    'We will be taking communion at the end of the service',
    'That is all I have for you this morning, God bless you',
    'Next week we will continue in this series on the family',
    'We will be having a baby dedication after the second service',
    'The prayer meeting has moved to Wednesday evening at seven',
    'Thank you to everyone who helped clean the building yesterday',
    'If you need a ride home please speak to one of the ushers',
    "The men's breakfast is on the first Saturday of the month",
    'Please keep the noise down in the corridors during service',
    'We are recording this message so you can share it later',
    'Can somebody bring a glass of water for the pastor',
    // Stories and illustrations.
    'I was driving here this morning and the traffic was terrible',
    'My grandmother used to cook rice every Sunday after church',
    'When I was in university I nearly gave up on everything',
    'Let me tell you a story about a man who lost his job',
    'My son asked me a question last week that I could not answer',
    'There was a woman in our village who sold tomatoes by the roadside',
    'I remember the day my father bought our first television',
    'The doctor told him he had six months to live',
    'We sat in that hospital waiting room for nine hours',
    'Some of you have been praying about that job for three years',
    'He lost his business, his car, and then his marriage',
    'My phone fell into the water and I thought it was over',
    'The bank refused the loan twice before it went through',
    'I met my wife at a wedding in Accra',
    'They told her she would never walk again',
    // Exhortation and God-talk without a verse behind it.
    'Some of you came in tired and that is okay',
    'We are going to pray for the sick at the end of the service',
    "I don't know about you but I came to worship today",
    'Life will throw things at you that you did not expect',
    'There are people in this room going through a hard season',
    'God is good all the time and all the time God is good',
    'We thank God for the life of our brother who passed away',
    'The Lord has been faithful to this church for twenty years',
    'Money is not everything but it helps',
    'Some of us are holding grudges against our own family',
    'Pray for our leaders and for the country',
    'You have been through the fire and you are still standing',
    "Don't give up on your marriage",
    'Every single one of us needs the grace of God',
    'Jesus loves you more than you know',
    'The enemy wants you to quit but you will not quit',
    'This is your season of breakthrough',
    'Your testimony is coming, just hold on',
    'God can turn your situation around in one day',
    'The Holy Spirit is moving in this place',
    'We need to pray more and complain less',
    'Somebody needs a miracle this morning',
    'Worship is not just a song, it is a lifestyle',
    'You are not what people say about you',
    'Let the church say amen',
    'We serve a God who answers prayer',
    'The blood of Jesus still works today',
    'Heaven is real and hell is real',
    'Your past does not define your future',
    'Forgiveness is a choice you make every day',
    'Give God the first fruits of your time',
    'Church, we are going to win this battle',
    'We give God all the glory for what he has done',
    'Do not let anybody steal your joy',
    'Salvation is free but it is not cheap',
    'Some of us need to repent today',
    'This church will grow and the gates will be full',
    'Prayer is the key to everything we do here',
    'He is a way maker and a promise keeper',
]
